import { Task } from "./types";

const today = new Date();
const d = (h: number, m = 0) => {
  const dt = new Date(today);
  dt.setHours(h, m, 0, 0);
  return dt.toISOString();
};

export const MOCK_TASKS: Task[] = [
  {
    id: 1,
    title: "朝のスタンドアップ",
    description: "チームとの進捗共有",
    priority: 1,
    is_completed: true,
    estimated_hours: 0.5,
    ai_estimated_hours: 0.5,
    ai_estimation_reason: null,
    start_time: d(9, 0),
    end_time: d(9, 30),
    due_date: null,
    achievement_rate: 100,
    category: { id: 1, name: "ミーティング", color: "#6366f1" },
  },
  {
    id: 2,
    title: "認証APIの実装",
    description: "JWTトークン検証ロジック",
    priority: 1,
    is_completed: false,
    estimated_hours: 2,
    ai_estimated_hours: 3.5,
    ai_estimation_reason: null,
    start_time: d(9, 30),
    end_time: d(11, 30),
    due_date: today.toISOString(),
    achievement_rate: 70,
    category: { id: 2, name: "開発", color: "#0ea5e9" },
  },
  {
    id: 3,
    title: "ランチ",
    description: null,
    priority: 3,
    is_completed: false,
    estimated_hours: 1,
    ai_estimated_hours: 1,
    ai_estimation_reason: null,
    start_time: d(12, 0),
    end_time: d(13, 0),
    due_date: null,
    achievement_rate: null,
    category: { id: 3, name: "休憩", color: "#f59e0b" },
  },
  {
    id: 4,
    title: "タイムブロッキング画面のUI実装",
    description: "コンポーネント設計とスタイリング",
    priority: 1,
    is_completed: false,
    estimated_hours: 3,
    ai_estimated_hours: 4,
    ai_estimation_reason: null,
    start_time: d(13, 0),
    end_time: d(16, 0),
    due_date: today.toISOString(),
    achievement_rate: null,
    category: { id: 2, name: "開発", color: "#0ea5e9" },
  },
  {
    id: 5,
    title: "コードレビュー",
    description: "PR #42 のレビュー",
    priority: 2,
    is_completed: false,
    estimated_hours: 1,
    ai_estimated_hours: 1.5,
    ai_estimation_reason: null,
    start_time: d(16, 0),
    end_time: d(17, 0),
    due_date: null,
    achievement_rate: null,
    category: { id: 2, name: "開発", color: "#0ea5e9" },
  },
  // Inbox (unscheduled) tasks
  {
    id: 6,
    title: "DBスキーマ設計レビュー",
    description: null,
    priority: 1,
    is_completed: false,
    estimated_hours: 1.5,
    ai_estimated_hours: 2,
    ai_estimation_reason: null,
    start_time: null,
    end_time: null,
    due_date: today.toISOString(),
    achievement_rate: null,
    category: { id: 2, name: "開発", color: "#0ea5e9" },
  },
  {
    id: 7,
    title: "週次レポート作成",
    description: null,
    priority: 2,
    is_completed: false,
    estimated_hours: 0.5,
    ai_estimated_hours: 0.5,
    ai_estimation_reason: null,
    start_time: null,
    end_time: null,
    due_date: null,
    achievement_rate: null,
    category: { id: 4, name: "管理", color: "#10b981" },
  },
  {
    id: 8,
    title: "ドキュメント更新",
    description: "API仕様書の更新",
    priority: 3,
    is_completed: false,
    estimated_hours: 1,
    ai_estimated_hours: 1,
    ai_estimation_reason: null,
    start_time: null,
    end_time: null,
    due_date: null,
    achievement_rate: null,
    category: { id: 5, name: "ドキュメント", color: "#8b5cf6" },
  },
];
